viiiiideoooooo.Translation.fr = { 
	"Hattrick CHPP server seems down, please retry later.": "Le serveur CHPP de Hattrick semble être hors ligne, merci de réessayer plus tard.",
	"Hattrick CHPP Authentication has failed, you must retry the whole process.": "L'authentification Hattrick via CHPP a échoué, vous devez refaire le processus complet.",
	"%s has joined": "%s s'est connecté",
	"Send": "Envoi",
	"Chat": "Chat",
	"Welcome on %s": "Bienvenue sur %s",
	"%s has left": "%s s'est déconnecté",
	"Bye!": "Salut !",
	"See you soon!": "A bientôt !",
	"Let's say... now ;-)": "Disons... de suite ;-)",
	"Join": "Rejoignez",
	"a room by choosing the name you want,": "un salon en choisissant son nom,",
	"share": "partagez",
	"it with your friends,": "le avec vos amis,",
	"enjoy": "profitez",
	"Viiiiideoooooo :-)": "de Viiiiideoooooo :-)",
	"Your room:": "Votre salon :",
	"Use webcam:": "Avec webcam :",
	"Sign in with Hattrick": "Connexion Hattrick",
	"Language:": "Langue :",
	"Sure? It will be less fun...": "Sûr ? Ça sera moins fun...",
	"Please choose a name": "Merci de choisir un nom",
	"Processing...": "Traitement...",
	"Welcome on Viiiiideoooooo!": "Bienvenue sur Viiiiideoooooo !",
	"Loading...": "Chargement...",
	"by": "par",
	"Download Google Chrome": "Télécharger Google Chrome",
	"We hope to support your current browser soon, but for now there is no other way to enjoy Viiiiideoooooo!": "Nous espérons supporter votre navigateur très bientôt, mais pour l'instant il n'y a pas d'autre moyen de profiter de Viiiiideoooooo!",
	"Retry": "Réessayer",
	"Error :(": "Erreur :(",
	"Viiiiideoooooo is free but needs support of its users, please disable your ads blocker": "Viiiiideoooooo est gratuit mais a besoin du support de ses utilisateurs, merci de désactiver votre bloqueur de pub",
	"Viiiiideoooooo is free but you can support it with just a click on ads at the top of the window, thank you very much!": "Viiiiideoooooo est gratuit mais vous pouvez l'aider juste avec un clic sur la pub en haut de l'écran, merci beaucoup !",
	"Viiiiideoooooo is free but needs support of its users, please disable your ads blocker and if you like Viiiiideoooooo you can click on ad from time to time, just one click ;-)": "Viiiiideoooooo est gratuit mais a besoin du support de ses utilisateurs, merci de désactiver votre bloquer de pub et si vous aimez Viiiiideoooooo vous pouvez cliquer sur la pub de temps en temps, juste un clic ;-)",
	"Overview": "Aperçu",
	"Add match": "Ajouter un match",
	"Live": "Live",
	"Add matches to your live": "Ajouter des matchs à votre live",
	"Lives are shared within all members of the room, each member can add different matches, everyone can watch all matches!": "Le live est partagé entre tous les membres du salon, chaque membre peut ajouter des matchs différents, tout le monde peut suivre tous les matchs !",
	"Senior Match": "Match de séniors",
	"Youth Match": "Match de jeunes",
	"Tournament Match": "Match de tournoi",
	"Senior Team": "Equipe sénior",
	"Youth Team": "Equipe jeune",
	"NT/U20 Team": "Equipe A/U20",
	"Type ID here": "Saisir l'ID ici",
	"Search": "Rechercher",
	"Invalid ID": "ID invalide",
	"Searching...": "Recherche...",
	"Not found. Check your ID and retry.": "Non trouvé. Vérifier votre ID et réessayer.",
	"No upcoming match for this team.": "Aucun match à venir pour cette équipe.",
	"Your Hattrick live is empty :(": "Votre live Hattrick est vide :(",
	"Add some matches to fill this box!": "Ajouter des matchs pour remplir cet emplacement !",
	"Remove": "Supprimer",
	"Listen": "Ecouter",
	"Kick-off in %s": "Coup d'envoi dans %s",
	"With its awesome features Viiiiiideoooooo requires last version of Google Chrome or Mozilla Firefox browser.": "Avec ses incroyables fonctionnalités Viiiiideoooooo requiert la dernière version du navigateur Google Chrome ou Mozilla Firefox.",
	"Download Mozilla Firefox": "Télécharger Mozilla Firefox"
};